services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: counterdb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: counterdb
    ports:
      - "5432:5432"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always
